services:
  - type: web
    name: astro-tienda
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: HOST=0.0.0.0 PORT=10000 node ./dist/server/entry.mjs
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: NPM_CONFIG_PRODUCTION
        value: false
      - key: NODE_ENV
        value: production
